<!DOCTYPE html>
<html>
<head>
	<title>Alkagolic</title>
</head>
<body style="margin:0;">
	<div style="border:4px black solid; height:15vh; text-align:center;">
		

<?php

// class Lempa{
// 	public function ijungti(){
// 		echo "Lempa Ijungta!";
// 	}
// 	public function isjungti(){
// 		echo "Lempa Isjungta";
// 	}
// }

// $lempa = new Lempa();
// $lempa->ijungti();


class Cars{
	public $name;
	public $color;
	public $year;
	public $horsepower;

	public function setName($name){
		$this->name = $name;
}


	public function setColor($color){
		$this->color = $color;
}


	public function setYear($year){
		$this->year = $year;
}


	public function setHorsepower($horsepower){
		$this->horsepower = $horsepower;
}




$masina = new Cars();
$masina->name = "Bulka";
$masina->color = 'Black';
$masina->year = '1999';
$masina->horsepower = '60hp';

$masina-> Parametrai();



?>

















	</div>
</body>
</html>






