<!DOCTYPE html>
<html>
<head>
	<title>Alkagolic</title>
</head>
<body style="margin:0;">
	<div style="border:4px black solid; height:15vh; text-align:center;">
		

<?php


class Masina
{
	private $name;
	private $price;
	private $color;
	private $rating;
	private $stock;

	public function getName($name){
		$this->name = $name;
	}

	public function getPrice($price){
		$this->price = $price;
	}

	public function getColor($color){
		$this->color = $color;
	}

	public function getRating($rating){
		$this->rating = $rating;
	}

	public function getStock($stock){
		$this->stock = $stock;
	}

	public function RETURN(){
		echo ("Masinos pavadinimas : " . $this->name);
		echo "<br>";
		echo ("Masinos kaina : " . $this->price);
		echo "<br>";
		echo ("Masinos spalva : " . $this->color);
		echo "<br>";
		echo ("Masinos reitingas : " . $this->rating);
		echo "<br>";
		echo ("Masinos STOCK : " . $this->stock);
		echo "<br>";
		echo "<br>";

	}

	public function removeNumbers($string){
		$sk = [1,2,3,4,5,6,7,8,9];
		$string2 = str_replace($sk, "" , $string);
		echo $string2;



		
	}

}



$masina1 = new Masina();
$masina1->getName("Audi");
$masina1->getPrice("$1600");
$masina1->getColor("Red");
$masina1->getRating("9.5");
$masina1->getStock("One of a kind");
$masina1->RETURN();

$sakinys = new Masina();
$sakinys->removeNumbers("I6spa76nija yr8a ah54ujen23a.");





?>
	</div>
</body>
</html>






