<?php
$colors = ['yellow', 'green','red'];
$colored = [ 'blue', 'black', '#FDF5E6'];
$colorado = [ 'black', 'red', 'yellow'];
$colorad = [ 'red', '#FDF5E6','red'];
$colorid = [ 'lightgrey','blue', 'red'];
$colours = [ 'navy','red','navy'];
$corors = [ 'brown','#FDF5E6','brown'];
$corours = [ 'red','#FDF5E6','green'];
$coroirs = [ 'red','#FDF5E6','cyan'];
$corurs = [ '#87CEFA','#FDF5E6','#87CEFA'];
?>
<!DOCTYPE html>
<html>
<head>
	<title>GContacts</title>
	<link rel="stylesheet" type="text/css" href="luko.css">
	<style>
body{
	background-color: #00FFFF;

}
		div{
			height: 20px;
			width: 100px;
          


		}
	</style>
</head>
<body>
	<div class="super">
	<h1> ¯\_(ツ)_/¯ ( ͡° ͜ʖ ͡°) Contacts ( ͡° ͜ʖ ͡°) ¯\_(ツ)_/¯</h1>
</div>
<br>
<div class="mano-container">
	<div class="contacts">
		<?php foreach($colors as $color): ?>
			<div style="background-color: <?= $color; ?>;"></div>
		<?php endforeach; ?>
		<h2> ʕ•ᴥ•ʔ Kontaktai</h2>
	</div>
	<div class="viet"> Namu numeris +37078354 nespaminkit jei ka     tlf nr: +3789375536 galite mus rasti oskabybiskiu gatveje</div>
	<div class="taip"> Jei norite mus sutikti specialiam pasiulimam arba uzsisakyti extra skambintike nr:+370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

	
<div class ="mano-container">
	<div class="contacts">
	<?php foreach($colored as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Kontaktid</h2>
</div>
<div class="viet"> Maja number +37078354 ära unusta, kui ka tlf nr: +3789375536 leiate meid tänaval </div>
	<div class="taip">Kui soovite saada eripakkumist või tellida lisakutsungi number: +370487634</div>
</div>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>







<div class ="mano-container">
	<div class="contacts">
	<?php foreach($colorado as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Kontakte</h2>
</div>
<div class="viet"> Hausnummer +37078354 nicht verpassen wenn tlf nr: +3789375536 finden Sie uns auf der Straße</div>
	<div class="taip"> Wenn Sie ein Sonderangebot erhalten oder eine zusätzliche Rufnummer bestellen möchten: +370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($colorad as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Kontakte</h2>
</div>
<div class="viet"> Hausnummer +37078354 nicht verpassen wenn tlf nr: +3789375536 finden Sie uns auf der Straße</div>
	<div class="taip">  Wenn Sie ein Sonderangebot erhalten oder eine zusätzliche Rufnummer bestellen möchten: +370487634</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($colorid as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ контакты</h2>
</div>
<div class="viet"> Номер дома +37078354 не пропустите, если по тел. +3789375536 вы можете найти нас на улице</div>
	<div class="taip">    Если вы хотите получить специальное предложение или заказать дополнительный номер для звонка: +370487634</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($colours as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Contacts</h2>
</div>
<div class="viet"> House number +37078354 do not miss if tlf nr: +3789375536 you can find us on the street kaladickens</div>
	<div class="taip"> If you would like to receive a special offer or order extra call number: +370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($corors as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Kontaktus</h2>
</div>
<div class="viet"> Mājas numurs +37078354 nepalaidiet garām, ja tlf nr: +3789375536 jūs varat atrast mūs uz ielas</div>
	<div class="taip">  Ja vēlaties saņemt speciālu piedāvājumu vai pasūtīt papildu zvanu numuru: +370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($corours as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Kontakty</h2>
</div>
<div class="viet"> Номер на къща +37078354 не пропускайте, ако сте на адрес: +3789375536 можете да ни намерите на улицата</div>
	<div class="taip">Ако желаете да получите специална оферта или поръчате допълнителен телефонен номер: +370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($coroirs as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Contactai</h2>
</div>
<div class="viet"> Hausnummer +37078354 Verpasst net wann tlf nr: +3789375536 Dir fannt eis op der Strooss</div>
	<div class="taip">  Wann Dir wëllt e spezielle Offer kréien oder bestellen extra Rufnummer: +370487634</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class ="mano-container">
	<div class="contacts">
	<?php foreach($corurs as $color): ?>
<div style="background-color: <?= $color; ?>;"></div>
<?php endforeach; ?>
	<h2> ʕ•ᴥ•ʔ Contactos</h2>
</div>
<div class="viet"> Número de casa +37078354 no se pierda si tlf nr: +3789375536 nos puede encontrar en la calle</div>
	<div class="taip"> Si desea recibir una oferta especial o pedir un número de llamada adicional: +370487634</div>
</div>

</body>
</html>